config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  resources :todos do
    resources :items
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :todo

  validates_presence_of :name
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :items, dependent: :destroy

  validates_presence_of :title, :created_by
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_note, only: [:show, :edit, :destroy, :update]
  def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.create!(todo_params)

    redirect_to action: "index"
  end

  def show
  end

  def update
    @todo.update(todo_params)
  end

  def destroy
    @todo.destroy
  end

  private
    
    def todo_params
      params.permit(:title, :created_by)
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.slim
h1 Welcome to our todo apps
= link_to 'todo', todos_path

app/views/layouts/_header.html.slim
h1 Header

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title ToDoPWA
    = csrf_meta_tags

    meta charset="UTF-8" /
    meta http-equiv="X-UA-Compatible" content="chrome=1" /
    meta name="viewport" content="width=device-width, initial-scale=1.0" /
    meta name="theme-color" content="#000000"/


    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reloads'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    link rel="manifest" href="/manifest.json" /
    meta name="apple-mobile-web-app-capable" content="yes"

  body
    = render partial: 'layouts/header'
    = yield 

app/views/todos/index.html.slim
- if(@todos.empty?)
    small There is no todo list

- @todos.each do |todo|
    h3 #{todo.title}
    h1 #{todo.created_by}
    ul
      - todo.items.each do |item|
        li #{item.name}